- hosts: k8s
  become: true
  roles:
    - common
    - containerd
    - kubeadm

- hosts: k8s_master
  become: true
  roles:
    - k8s-master

- hosts: k8s_worker
  become: true
  roles:
    - k8s-worker
